env:
    TZ: ENC[AES256_GCM,data:W+Ug,iv:f4vlqOuUB/zlXvMRYvkFyA7fXH1E+NK3weNxxNs67fg=,tag:kGjjeoeb6098dr1dYoD8sA==,type:str]
    GOTIFY_DEFAULTUSER_NAME: ENC[AES256_GCM,data:v+rX,iv:WJNo9rBA0Er/qSxXz69nMFiTUyPWIlIyOZVGLuKarFY=,tag:agoSjVUniF3wu0OBN9BayQ==,type:str]
    GOTIFY_DEFAULTUSER_PASS: ENC[AES256_GCM,data:eJCsqzc0OwgmOm4lolgzBHPJj/aoeu0rAxAnef9yR9A0sdJsEZE7F+na,iv:Hpt1zkdJsb39JrPoipxj3Ay66UQhRtnvA2t9W4EhZnk=,tag:KC0iR4hM6S1ZsVeMZKVafw==,type:str]
    GOTIFY_REGISTRATION: ENC[AES256_GCM,data:q4jLqQQ=,iv:Jqu80W1OEZYztrSqBwx87ibcJJ8B6HX4xJ3kEGSdof8=,tag:GrWzpsfuE2yS9Tay+3guTQ==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-3caeb0533c5a473f.vault.azure.net
          name: sops-key
          version: b2031a08aea14a50ab6d8e72548eb4f9
          created_at: "2023-12-15T09:30:21Z"
          enc: n-ihrcDFBoY7xiWYttVr49-BUP7QhtM4T4tuWTt9OeSWlZuRtty-1WwWtKzErzicVmT6wrLzGPOVHpxeZgOKsnzMfQhSZ9q_MWAkXfKhMSPM4o36W0sGQqAmHiwdwZTudVus9ncPQO2KuElvf4oUDRV0DsuI0XK11pzQKFr2InjpF3-f1Egk39aGcK6AG6eLyRlia5UJxremp4srUDzzxqE4LP9bJVek-xx2VGqSPb-AgfSp6sqsWM4L-vhj_szdcfJLq5HaEc8KCONfIZbqYm9LhKbdHpHU2fPMmDZX1JX_Yzj2vO9ERTfY6wZX137M-A9-EjYPCszBWAf_ZrnaEg
    hc_vault: []
    age: []
    lastmodified: "2023-12-15T09:30:22Z"
    mac: ENC[AES256_GCM,data:RNV3/u1t8Ey741P9Vd9WMRB1Si7D/c57+OGGzIIn+abEVwJ48qZVLb0/990tWl1WJff81tohToQuTYQh4GYWTRJHtbrhzfrdGTEDsdX+21P5n+SAJUYoepTI1wOwHwLSqSxzjlj4ijZ1V1WMbLOb3JrNFXOEavRdy3yq3FAexp0=,iv:LRG9GCISEbRYUNLvp/xaEcsECyIvWhGYRhb/1wDs0fo=,tag:UPgq64np33XJn7IlsfnoUw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
