apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config-override
  namespace: cattle-monitoring-system
spec:
  route:
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: gotify_alertmanager_bridge
    routes:
      - matchers:
        - name: severity
          value: none
        receiver: 'null'
  receivers:
    - name: "null"
    - name: gotify_alertmanager_bridge
      webhookConfigs:
        - sendResolved: true
          httpConfig:
            followRedirects: true
          url: "http://alertmanager-gotify-bridge.gotify.svc.cluster.local:8080/gotify_webhook"