[tools]
helm = "3.17.2"
kubeconform = "latest"
kubectl = "1.33.2"
kustomize = "5.7.0"
"pipx:codespell" = "2.4.1"
"pipx:yamllint" = "1.37.0"
shellcheck = "0.11.0"

[hooks]
enter = "mise i -q"
postinstall = "mise run init"
