apiVersion: v1
kind: Service
metadata:
    name: rke2-ingress-nginx-controller-loadbalancer
    namespace: kube-system
spec:
    type: LoadBalancer
    loadBalancerIP: ENC[AES256_GCM,data:xBXcGpNhsr1AOeIiMA==,iv:ls1SVN5//1CG5Z5995apHd6t5fB+kuQUMdJ8jB0YQ/U=,tag:XQdpecyljRIrPrlRWilL3A==,type:str]
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 80
        - name: https
          port: 443
          protocol: TCP
          targetPort: 443
    selector:
        app.kubernetes.io/instance: rke2-ingress-nginx
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-3caeb0533c5a473f.vault.azure.net
          name: sops-key
          version: b2031a08aea14a50ab6d8e72548eb4f9
          created_at: "2023-12-16T11:59:39Z"
          enc: MvwmK5oHNjw1-X12xi-1_iEe2F-Q1CKQUZkeQ_8xzh2SSbfH7ssUjb6DXZjQ6CoqT1YkRdyMGQ0QLTbDN69w8VjnraiBaHkIE8Rt3YJB20jEXGVPXMv6sqT5KP7Of9z-u0lG4I19T4E5o4VG5qk7450E9Ab5G2c8MthUolIzpMiarx4B1pJ_6FN46Rsj6QbLwzziUC6uFr82VdHAH1Pe0p5xUoy6wO9_II25w70jq6BbwvKB_S4qKLzVyeNUxgpMWc7qfB9EXlCMG9LJtC-apFdPlHuajZyweePq8MiQkitRSAzyDAtnwxvrWCb-AtNiNnVclbHNFqGDNF-ZqVAc5A
    hc_vault: []
    age: []
    lastmodified: "2023-12-16T11:59:39Z"
    mac: ENC[AES256_GCM,data:JnqzQXirrHiTj+zEuvGkl0tWSZ5BMnUey8C/BmVEXUJgOZDmByTQy4yPT7J1YmgAP/WfAbxchm+072qkWOs8HCJPV4t6NGMUvkWfOfrYv/94wfw14rSbB5UjK0d1QeMbrCDxfCoIp8dzdjVO7HSs3DfpP36RsUFecNhZvqGyy0Y=,iv:UohHR6BdntswvocGSw0CITZXFp1R4nqNH5qiopfDBCA=,tag:G6Cyy1DtBV8UVuxxze+pdw==,type:str]
    pgp: []
    encrypted_regex: ^(loadBalancerIP)$
    version: 3.7.3
