apiVersion: ENC[AES256_GCM,data:p1174h8Dbg==,iv:9rpzuZrgAd3vsA3DLzYcaLyDuUQewCHYMCbAJHSkyqQ=,tag:xZb94qWOzxE5Xd4bM6uuTw==,type:str]
kind: ENC[AES256_GCM,data:+LYt5izBsEmMNQ==,iv:ytVF0PsYpQQb4Qe3f03PmP3XRsQkxvzI4xVTyIXPcjE=,tag:Q5N349l/Vx08ZGtVi1yUOg==,type:str]
metadata:
    labels:
        app: ENC[AES256_GCM,data:tF96O2URB/jnH4FPJ2zS2REBIHQbfzrOIw8=,iv:otDrVneZYtyBxTGUPO7M6vZ6Kp92NqMpO+31ruCjQlw=,tag:rhoX8R5pEueUyGilxFYc1Q==,type:str]
    name: ENC[AES256_GCM,data:BQbfOGjX+SzCI9WImuuwWOyLoaMABy/D9T0=,iv:meAFU5tMZOYYGxwfudkKYqJau6YhmTl7OmYJGe1OE+c=,tag:Y7lY8CDXXxILuwZv006yrw==,type:str]
    namespace: ENC[AES256_GCM,data:aixHMldt,iv:3JVkFiUiZgoPNfbQV9c8vVFxoG5j0Ef42Hll2w9W6VA=,tag:EBTaqBwxrnmYAP6xLHDP7w==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:BA==,iv:YlKBRnMfWehnP8Z+rBUyGBvtrEmesFyzyYDfz0glDvI=,tag:+iJNlXDjKPxU7KdW3ReXeg==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:aWAsWMTwTI5pGYmLglhry457/GdDynUx51w=,iv:N2eA7T9Jo+NEf8Y8RoW2+xpMQCp8gR+iS/t2JNOt5HU=,tag:JWPfMrveaXqRhro19HQEKQ==,type:str]
    strategy: {}
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:+7mx6Y7gd5B6qFMwQ+jQmz95Ss9AApg1kGQ=,iv:kI6LBpqxM1RgNXTJUUQX24kcgfoup210eOAj3UxR7Ew=,tag:wlqvkzmYfi/VrHTEfiX3BQ==,type:str]
        spec:
            containers:
                - image: ENC[AES256_GCM,data:nnZh9XQJ3vt0+TTC41Trs8X/C/w7U9AdedEWvKHInC27Oc46EMi7YwU=,iv:ZIlpTy/PneBGNOYvw45SznpdXZVaWhSrdOdWrcs6e/8=,tag:jGck5+Xn0xC3n2SbSYKCHg==,type:str]
                  name: ENC[AES256_GCM,data:1UXgxNAU+767bQbD6uxL9uB/SvuRWL2uqWVa3YJkiIA=,iv:4twjw/epV4/GnxnOa1aPEfgVQVAsOGCMpPnZs/GfPTQ=,tag:8YExWnmbc5cSx+lkdr7VdA==,type:str]
                  resources: {}
                  ports:
                    - containerPort: ENC[AES256_GCM,data:1ZBNDw==,iv:saK9LLzF/9XNPmfzTP5QquXYmum8OKZBMUhMY5fbLKs=,tag:+O5txWUkUhzqcv7dXrbAfA==,type:int]
                      name: ENC[AES256_GCM,data:qZpayPB6MvAjGY4=,iv:tI3hoDZ1eA3bTuZpC2hztBexeXkvdD6m2gbX+rqF0uE=,tag:gWEF5j51lQvLF/hD8H0yOA==,type:str]
                      protocol: ENC[AES256_GCM,data:lHel,iv:R1IYEhzwk1rRxTSNvQMb2iYzEM/DVW0AEeAyhd21RUA=,tag:G8qyqxpR7Vd+IC8LzM+06A==,type:str]
                  env:
                    - name: ENC[AES256_GCM,data:alFlioXq3R/501+q,iv:wbQCLr/faG0oO8qj7noDwRWRG95ZmB0PkyR2FhF9oP8=,tag:UZeNXfYaYQFYfxMcoFxY7w==,type:str]
                      value: ENC[AES256_GCM,data:CvQiIQasdPBxJzkgzLRO,iv:YaD4YO+BdX8/vdxadZMpdO2ryUqWtBM/WUNrs7Uw/dY=,tag:L9j1rmYoNHBr03Ra2HEA+A==,type:str]
                    - name: ENC[AES256_GCM,data:nof2ifoJhfb1HZZtJTZI,iv:Ai3tXYtPAnCHKZYzdUQ3bS+QhoUZbBRGr2WfoVPZxhQ=,tag:mBT63uYLDDikTSwEdwOtNw==,type:str]
                      value: ENC[AES256_GCM,data:CEKddca3ZaBv5gX63FVdEOtexs5K,iv:dQM7AMa1oKhiLVSvGvFjddRINN+y655X72SXlhYHfLs=,tag:2T2eAXO4ifDmaXLGyJvn6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-3caeb0533c5a473f.vault.azure.net
          name: sops-key
          version: b2031a08aea14a50ab6d8e72548eb4f9
          created_at: "2024-03-03T09:22:00Z"
          enc: t1SLR7iz9IA-j0mqxc3PZjUIqkzTNMQe8NU3qBMWu4tb_Tm9_Y1B8dzlRcsZd1vgQjWmaakkPLvOKeMTXs01QSgXwQqes_aDrzXnOsv2EUNMZye9-2W9AQJqonE3TQos-e6p3sorzqt22v0ifU8mc4h-eUjJHRe8CiDFemLhz5Qdq-g7P785Oap5vaBD3WPlqYN7-SUNR1awV0DY0kQ_IHlmpNjax6x1QuiP4MDLiTsjtvMLsadQxC06TxOsPLJCAi-gKe78n9E5NrdRDkTezuBm-AHp7mMKosh7ZVz9bs9NUdG4-sY7OOjysX-D8vab4-PDUlHQbx_v4TOWCXUjgQ
    hc_vault: []
    age: []
    lastmodified: "2024-03-03T09:22:01Z"
    mac: ENC[AES256_GCM,data:DpFDnpWJts+dQ5K6RTRIkqmtTvK5fZZyQtVnbhliWsfUlA1qCT//Nf5pxM5fzRt22vRlX7KNhYAZQWzxlRHrDGV2T08R2Mm43gQ8WvOX3oq0alkvZXf2syxHI/9YRNE5uSUAre8ZHwfe1RZOpkczuf4vA+RjumHNzycR6Py1s1g=,iv:V4o1RPJV28maS/QCYZXRRwcSUQxeZ+6ql8+km2JLOV8=,tag:NAb4rErnPMDU97IMj03lSQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
